### PR TITLE
Add support for variable scopes

### PR DESCRIPTION
**Pull request by florentinw**
This pull requests add support for variable scopes by introducing an `com.figma` property to the `$extensions` attribute &           exposing all available scopes under the `scopes` key.

### Usage
```
"black": {
   "$type": "color",
   "$value": "#000",
   "$extensions": {
      "com.figma": {
         "scopes": ["FRAME_FILL", "SHAPE_FILL"]
      }
   }
}
```

[List of available Figma Variable Scopes](https://www.figma.com/plugin-docs/api/VariableScope/)

### CODE REVIEW

**Comment by TravisSpomer** [comment]
Apologies for missing this! I didn't have this repo marked "watched."

Looks good overall! I have two small thoughts:

* Using `com.figma` without me actually working for Figma feels mildly evil. Let me run it by someone there and see if they already had any thoughts on how this should work.
* I'd been planning on doing this with a simpler "purpose" property that just supported "foreground", "background", and "stroke". Background would translate to `["FRAME_FILL", "SHAPE_FILL"]` like in your example. But now I'm thinking it probably makes more sense to just do something Figma-specific since I don't have any other concrete requirements.

**Comment by TravisSpomer** [comment]
This is now in the latest version of the released plugin, version 5. (I only mentioned `$description` in the notes, but scopes are there too.)

**Comment by raphtastisch** [comment]
@Travis Important: This apparently breaks the import of strings. I would be very glad if you could fix it or roll this back to the state from yesterday. The same imports as yesterday don't work anymore and even a test with an import of a single string  variable fails. 

Error message: "Failed to import the token files: in set_scopes: Cannot set scopes on this variable type"

I think the reason is that Figma only supports scoping for numbers(https://help.figma.com/hc/en-us/articles/15145852043927-Create-and-manage-variables) - not sure why it works with colors despite this info on the figma homepage:
"Scope a variable
Currently, scoping is available for number variables and will expand to additional variables in the future."


Further context, this is the simple testfile i used:
{
    "newstring": {
        "$type": "string",
        "$value": "safdsadf"
    }
}

**Comment by TravisSpomer** [comment]
Whoops, sorry about that! That's what I get for having a test file that only includes colors and numbers. I published a new version just now that fixes those token types. Thanks for reporting this!

**Pull request merged**
